image: elixir:1.13
build:
  stage: build
  variables:
    MIX_ENV: "test"
  script:
    - apt-get update
    - apt-get install -y build-essential automake autoconf pkg-config bc m4 unzip zip curl git libssl-dev libncurses5-dev ca-certificates cmake
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix test
