#!/bin/bash
# Write checksum.term from the assets of a published release.
#
# The tarballs only exist after the v* tag has been pushed and the precompile
# matrix has finished, so this runs between tagging and `rebar3 hex publish` --
# the manifest has to be inside the published package, since it is what the
# package checks its downloads against.
#
#     scripts/generate_checksums.sh 0.4.0
#     git add checksum.term && git commit && rebar3 hex publish

set -euo pipefail

VERSION="${1:?usage: scripts/generate_checksums.sh <version, e.g. 0.4.0>}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

if command -v sha256sum > /dev/null 2>&1; then
  sha256() { sha256sum "$1" | cut -d' ' -f1; }
elif command -v shasum > /dev/null 2>&1; then
  sha256() { shasum -a 256 "$1" | cut -d' ' -f1; }
else
  echo "need sha256sum or shasum" >&2
  exit 1
fi

echo "Downloading the assets of v${VERSION}..."
gh release download "v${VERSION}" --repo cocoa-xu/tflite_beam --dir "$WORK_DIR" --pattern '*.tar.gz'

COUNT="$(find "$WORK_DIR" -name '*.tar.gz' | wc -l | tr -d ' ')"
if [ "$COUNT" -eq 0 ]; then
  echo "v${VERSION} has no tarballs; has the precompile matrix finished?" >&2
  exit 1
fi

{
  echo "%% sha256 of every precompiled tarball published for v${VERSION}."
  echo "%% Generated by scripts/generate_checksums.sh -- do not edit by hand."
  for tarball in "$WORK_DIR"/*.tar.gz; do
    printf '{"%s", "%s"}.\n' "$(basename "$tarball")" "$(sha256 "$tarball")"
  done
} > "${REPO_ROOT}/checksum.term"

echo "Wrote ${COUNT} checksums to checksum.term"
