#!/bin/bash
# Write checksum.term from the assets of a published release.
#
# The tarballs only exist after the v* tag has been pushed and the precompile
# matrix has finished, so this runs between tagging and `rebar3 hex publish` --
# the manifest has to be inside the published package, since it is what the
# package checks its downloads against.
#
#     scripts/generate_checksums.sh 0.4.0
#     git add checksum.term && git commit && rebar3 hex publish

set -euo pipefail

VERSION="${1:?usage: scripts/generate_checksums.sh <version, e.g. 0.4.0>}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

if command -v sha256sum > /dev/null 2>&1; then
  sha256() { sha256sum "$1" | cut -d' ' -f1; }
elif command -v shasum > /dev/null 2>&1; then
  sha256() { shasum -a 256 "$1" | cut -d' ' -f1; }
else
  echo "need sha256sum or shasum" >&2
  exit 1
fi

echo "Downloading the assets of v${VERSION}..."
gh release download "v${VERSION}" --repo cocoa-xu/tflite_beam --dir "$WORK_DIR" --pattern '*.tar.gz'

# Every target, named rather than counted. A manifest that covers six of the seven
# is worse than none: the seventh refuses to install, and the six that verify give
# no hint why. This is also the check that stops a stale or partial manifest going
# out, which is the whole reason the installer can refuse a file it does not name.
EXPECTED_TARGETS=(
  aarch64-apple-darwin
  aarch64-linux-gnu
  armv6-linux-gnueabihf
  armv7l-linux-gnueabihf
  riscv64-linux-gnu
  x86_64-apple-darwin
  x86_64-linux-gnu
)

COUNT="$(find "$WORK_DIR" -name '*.tar.gz' | wc -l | tr -d ' ')"
if [ "$COUNT" -eq 0 ]; then
  echo "v${VERSION} has no tarballs; has the precompile matrix finished?" >&2
  exit 1
fi

# Two variants per target since 1.0.0: the ordinary build and one with the
# LiteRT API compiled in, chosen at install time by TFLITE_BEAM_ENABLE_LITERT_API.
# Both have to be named here. A manifest that lists only the plain ones lets the
# LiteRT half refuse to install, with no hint that the release built them.
#
# armv6 and armv7l are the exception and get no LiteRT tarball: they build with
# XNNPACK off, LiteRT's CPU accelerator is XNNPACK, and the resulting .so does
# not load. Expecting one here would block every release for a file the matrix
# is right not to produce.
LITERT_TARGETS=()
for target in "${EXPECTED_TARGETS[@]}"; do
  case "$target" in
    armv6-*|armv7l-*) ;;
    *) LITERT_TARGETS+=("$target") ;;
  esac
done

MISSING=()
for target in "${EXPECTED_TARGETS[@]}"; do
  if ! find "$WORK_DIR" -name "*-${target}-v${VERSION}.tar.gz" | grep -q .; then
    MISSING+=("$target")
  fi
done
for target in "${LITERT_TARGETS[@]}"; do
  if ! find "$WORK_DIR" -name "*-${target}-litert-v${VERSION}.tar.gz" | grep -q .; then
    MISSING+=("${target}-litert")
  fi
done
if [ "${#MISSING[@]}" -ne 0 ]; then
  echo "v${VERSION} is missing tarballs for: ${MISSING[*]}" >&2
  echo "Publishing with a partial manifest makes those targets refuse to install." >&2
  exit 1
fi

# and nothing from another release, which is how 0.4.0-rc4 went out carrying
# rc3's manifest
STRAY="$(find "$WORK_DIR" -name '*.tar.gz' ! -name "*-v${VERSION}.tar.gz" -print -quit)"
if [ -n "$STRAY" ]; then
  echo "not a v${VERSION} tarball: $(basename "$STRAY")" >&2
  exit 1
fi

{
  echo "%% sha256 of every precompiled tarball published for v${VERSION}."
  echo "%% Generated by scripts/generate_checksums.sh -- do not edit by hand."
  for tarball in "$WORK_DIR"/*.tar.gz; do
    printf '{"%s", "%s"}.\n' "$(basename "$tarball")" "$(sha256 "$tarball")"
  done
} > "${REPO_ROOT}/checksum.term"

echo "Wrote ${COUNT} checksums to checksum.term"
