name: linux-precompile

on:
  push:
    tags:
      - 'v*'
      - 'precompile-test'
      - 'precompile-test-linux'

jobs:
  precompile:
    runs-on: ubuntu-20.04
    env:
      TFLITE_ELIXIR_PREFER_PRECOMPILED: NO
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              arch_name: x86_64
              cmake_toolchain_file: ""
              c_compiler: gcc
              cpp_compiler: g++
              libedgetpu_library: "x86_64"
              target_arch: "x86_64"
              target_os: "linux"
              target_abi: "gnu"
          - pair:
              arch_name: aarch64
              cmake_toolchain_file: cc_toolchain/aarch64-linux-gnu.cmake
              c_compiler: gcc-aarch64-linux-gnu
              cpp_compiler: g++-aarch64-linux-gnu
              libedgetpu_library: "aarch64"
              target_arch: "aarch64"
              target_os: "linux"
              target_abi: "gnu"
              cc: "/usr/bin/aarch64-linux-gnu-gcc"
              cxx: "/usr/bin/aarch64-linux-gnu-g++"
          - pair:
              arch_name: armv7l
              cmake_toolchain_file: cc_toolchain/armv7l-linux-gnueabihf.cmake
              c_compiler: gcc-arm-linux-gnueabihf
              cpp_compiler: g++-arm-linux-gnueabihf
              libedgetpu_library: "armv7a"
              target_arch: "arm"
              target_os: "linux"
              target_abi: "gnueabihf"
              cc: "/usr/bin/arm-linux-gnueabihf-gcc-9"
              cxx: "/usr/bin/arm-linux-gnueabihf-g++-9"
          - pair:
              arch_name: riscv64
              cmake_toolchain_file: cc_toolchain/riscv64-linux-gnu.cmake
              c_compiler: gcc-riscv64-linux-gnu
              cpp_compiler: g++-riscv64-linux-gnu
              libedgetpu_library: "riscv64"
              target_arch: "riscv64"
              target_os: "linux"
              target_abi: "gnu"
              cc: "/usr/bin/riscv64-linux-gnu-gcc"
              cxx: "/usr/bin/riscv64-linux-gnu-g++"

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.3"
          elixir-version: "1.14.3"

      - name: Install system dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential automake autoconf pkg-config bc m4 unzip zip curl git libssl-dev gzip libncurses5-dev ca-certificates ${{ matrix.pair.c_compiler }} ${{ matrix.pair.cpp_compiler }}

      - name: Create precompiled library
        run: |
          if [ "${{ matrix.pair.cmake_toolchain_file }}" != "" ]; then
            export CMAKE_TOOLCHAIN_FILE="$(pwd)/${{ matrix.pair.cmake_toolchain_file }}"
            export CC="${{ matrix.pair.cc }}"
            export CXX="${{ matrix.pair.cxx }}"
            export TARGET_ARCH="${{ matrix.pair.target_arch }}"
            export TARGET_OS="${{ matrix.pair.target_os }}"
            export TARGET_ABI="${{ matrix.pair.target_abi }}"
          fi

          export TFLITE_ELIXIR_PREFER_PRECOMPILED="NO"

          echo "CMAKE_TOOLCHAIN_FILE: ${CMAKE_TOOLCHAIN_FILE}"
          echo "TFLITE_ELIXIR_CORAL_LIBEDGETPU_LIBRARIES: ${TFLITE_ELIXIR_CORAL_LIBEDGETPU_LIBRARIES}"
          echo "TFLITE_ELIXIR_PREFER_PRECOMPILED: ${TFLITE_ELIXIR_PREFER_PRECOMPILED}"
          echo "CC: ${CC}"
          echo "CXX: ${CXX}"
          echo "TARGET_ARCH: ${TARGET_ARCH}"
          echo "TARGET_OS: ${TARGET_OS}"
          echo "TARGET_ABI: ${TARGET_ABI}"

          mix deps.get
          mix compile
          export PKG_NAME=tflite_elixir-${{ matrix.pair.arch_name }}-${{ matrix.pair.target_os }}-${{ matrix.pair.target_abi }}-${GITHUB_REF##*/}
          mkdir -p "${PKG_NAME}"
          cp -a _build/dev/lib/tflite_elixir/priv "${PKG_NAME}"
          tar -czf "${PKG_NAME}.tar.gz" "${PKG_NAME}"
          rm -rf "${PKG_NAME}"
          ls -lah "${PKG_NAME}.tar.gz"
          mkdir -p artifacts
          mv "${PKG_NAME}.tar.gz" artifacts

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/tflite_elixir-*.tar.gz
