name: macos-x86_64

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'examples/**/*.livemd'
      - 'examples/*.livemd'
  push:
    branches:
      - main
      - test-*
      - macos-ci-*
    paths-ignore:
      - '**/*.md'
      - 'examples/**/*.livemd'
      - 'examples/*.livemd'
      - 'nerves/**'
      - '.github/FUNDING.yml'
      - '.github/workflows/nerves-*'
      - '.github/workflows/linux-*.yml'
      - '.github/workflows/macos-precompiled.yml'
      - '.github/workflows/test-*.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rebar3_compile:
    runs-on: macos-11
    env:
      TFLITE_BEAM_CORAL_SUPPORT: "true"
      TFLITE_BEAM_PREFER_PRECOMPILED: "false"

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Erlang and Elixir
        run: |
          brew install erlang
          brew install elixir
          mix local.hex --force
          mix local.rebar --force
          wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
          ./rebar3 local install
          brew install autoconf automake

      - name: Compile
        run: |
          export PATH="~/.cache/rebar3/bin:$PATH"
          rebar3 deps
          rebar3 compile
