name: macos-precompile

on:
  push:
    tags:
      - 'v*'
      - 'precompile-test'
      - 'precompile-test-macos'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  precompile:
    runs-on: macos-11
    env:
      MIX_ENV: prod
      TFLITE_BEAM_PREFER_PRECOMPILED: "NO"

    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              arch: x86_64
              libedgetpu_library: darwin_x86_64
          - pair:
              arch: aarch64
              libedgetpu_library: darwin_arm64

    steps:
      - uses: actions/checkout@v3

      - name: Install Erlang and Elixir
        run: |
          brew install elixir erlang autoconf automake
          mix local.hex --force
          mix local.rebar --force

      - name: Create precompiled library
        run: |
          export NIF_VERSION="$(erl -noshell -s init stop -eval "io:format('~ts', [erlang:system_info(nif_version)]).")"
          if [ "${{ matrix.pair.arch }}" = "aarch64" ]; then
            export TARGET_ARCH="${{ matrix.pair.arch }}"
            export TARGET_OS="apple"
            export TARGET_ABI="darwin"
            export CPPFLAGS="-arch arm64"
            export CMAKE_TFLITE_OPTIONS="-DCMAKE_OSX_ARCHITECTURES=arm64"
            export TFLITE_BEAM_CORAL_LIBEDGETPU_LIBRARIES="aarch64"
          fi

          echo "TFLITE_BEAM_PREFER_PRECOMPILED: ${TFLITE_BEAM_PREFER_PRECOMPILED}"
          echo "TARGET_ARCH: ${TARGET_ARCH}"
          echo "TARGET_OS: ${TARGET_OS}"
          echo "TARGET_ABI: ${TARGET_ABI}"

          mix deps.get
          mix compile
          export PKG_NAME=tflite_beam-nif-${NIF_VERSION}-${{ matrix.pair.arch }}-apple-darwin-${GITHUB_REF##*/}
          mkdir -p "${PKG_NAME}"
          cp -a _build/${MIX_ENV}/lib/tflite_beam/priv "${PKG_NAME}"
          tar -czf "${PKG_NAME}.tar.gz" "${PKG_NAME}"
          rm -rf "${PKG_NAME}"
          mkdir -p artifacts
          mv "${PKG_NAME}.tar.gz" artifacts

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/tflite_beam-*.tar.gz
