name: macos-precompile

on:
  push:
    tags:
      - 'v*'
      - 'precompile-test'
      - 'precompile-test-macos'

jobs:
  mix_test:
    runs-on: macos-11
    env:
      MIX_ENV: dev

    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              arch: x86_64
              libedgetpu_library: darwin_x86_64
          - pair:
              arch: arm64
              libedgetpu_library: darwin_arm64

    steps:
      - uses: actions/checkout@v2

      - name: Install Erlang and Elixir
        run: |
          brew install elixir erlang autoconf automake
          export SRC_ROOT="$(pwd)"
          cd ..
          mix local.hex --force
          mix local.rebar --force
          cd "${SRC_ROOT}"

      - name: Create precompiled library
        run: |
          if [ "${{ matrix.pair.arch }}" = "arm64" ]; then
            export TARGET_ARCH="${{ matrix.pair.arch }}"
            export TARGET_OS="apple"
            export TARGET_ABI="darwin"
            export CPPFLAGS="-arch arm64"
            export CMAKE_TFLITE_OPTIONS="-DCMAKE_OSX_ARCHITECTURES=arm64"
          fi
          export TFLITE_ELIXIR_PREFER_PRECOMPILED="NO"

          echo "TFLITE_ELIXIR_PREFER_PRECOMPILED: ${TFLITE_ELIXIR_PREFER_PRECOMPILED}"
          echo "TARGET_ARCH: ${TARGET_ARCH}"
          echo "TARGET_OS: ${TARGET_OS}"
          echo "TARGET_ABI: ${TARGET_ABI}"

          mix deps.get
          mix compile
          export PKG_NAME=tflite_elixir-${{ matrix.pair.arch }}-apple-darwin-${GITHUB_REF##*/}
          mkdir -p "${PKG_NAME}"
          cp -a _build/dev/lib/tflite_elixir/priv "${PKG_NAME}"
          zip -r -9 -y "${PKG_NAME}.zip" "${PKG_NAME}"
          rm -rf "${PKG_NAME}"
          ls -lah "${PKG_NAME}.zip"
          mkdir -p artifacts
          mv "${PKG_NAME}.zip" artifacts

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/tflite_elixir-*.zip
